---
article_type: article
author: "Maarja Olesk"
lang: et
news_title: "Ikka need isikuandmed"
preview: "Kus avaandmetest juttu, seal kerkib varem või hiljem küsimus isikuandmete kaitsest. Kas isikuandmete kaitsmiseks tuleks andmekraanid kinni keerata? Kuidas avaandmete avaldamisel kindel olla, et kellegi isiklik elu avatusega pihta ei saa? Advokaadid Liisi Jürgen ja Siiri Vello selgitasid detsembris toimunud töötoas, kuidas ava- ja isikuandmete maailmas orienteeruda."
preview_img: gdpr.jpg
submitted: 2020/02/21
tags:
  - avaandmed
  - isikuandmed
  - GDPR
  - Avaliku teabe seadus
text: '<p><b>Kus avaandmetest juttu, seal kerkib varem või hiljem küsimus isikuandmete kaitsest. Kas isikuandmete kaitsmiseks tuleks andmekraanid kinni keerata? Kuidas avaandmete avaldamisel kindel olla, et kellegi isiklik elu avatusega pihta ei saa? Advokaadid Liisi Jürgen ja Siiri Vello selgitasid detsembris toimunud töötoas, kuidas ava- ja isikuandmete maailmas orienteeruda.</b></p>
<p>Alustuseks tuletasid eksperdid meelde, et avalikkuse ja avatuse perspektiivist saab andmed jagada laias laastus kolmeks: 1) isikuandmed (sh eriliigilised isikuandmed ehk vanas kõnepruugis delikaatsed isikuandmed), 2) avalik teave ja 3) avaandmed. On ehk huvitav tõik, et andmetel kui sellistel ei ole õiguslikkus mõttes omanikku – nad ei kuulu otseselt kellelegi. Kui aga kasutame neid nii, et need muutuvad teosteks või kui need on mingil kujul korrastatud ja süstematiseeritud, saame juba hakata rääkima õigustest andmetele, andmebaasidele, kogumitele. Seejuures kehtib oluline põhimõte: andmesubjektil (ehk sel, kelle kohta need andmed käivad) peab olema võim oma isikuandmete üle. Seda võimu saab piirata ainult seadustest tulenevatel alustel.</p>
<h3>Mis siis ikkagi on isikuandmed?</h3>
<p>Isikuandmed on <b>kõik andmed, mis võimaldavad füüsilist isikut otse või kaudselt tuvastada</b>. Ammendavat loetelu sellistest andmetest ei ole võimalik anda (kõik sõltub kontekstist), aga tüüpilised isikuandmed on näiteks nimi, kontaktandmed või isikule iseloomulikud välised tunnused. Näiteks kvalifitseerub inimesest tehtud foto igal juhul isikuandmeteks; kui aga foto on nii detailne, et sellelt on tuvastatavad ka biomeetrilised tunnused (näojooned, silmaiiris), võib fotot pidada suisa eriliiki isikuandmeteks.</p>
<p>Nagu öeldud, on isikuandmete puhul tähtis kontekst: kui kodanik X-i sünnikuupäev on avaldatud üleriigilises ajalehes ilma nime ja muude andmeteta, ei loeta neid veel isikuandmeteks – lehelugejal ei ole võimalik pelgalt sünnikuupäeva järgi kõigi maailma inimeste seast konkreetset isikut tuvastada. Kui sama sünnikuupäev avaldada aga näiteks väikeses grupis, kus X-i nimi ja sünniaeg on hästi teada, saab sünnikuupäeva käsitada isikuandmetena, sest selles kontekstis on võimalik sünnikuupäeva järgi konkreetne isik kerge vaevaga tuvastada.</p>
<p>Isikuandmed, muide, saavad olla ainult füüsilistel isikutel – juriidilise isiku andmed ei liigitu isikuandmeteks mitte üheski kontekstis. Nii näiteks ei kehti ka juriidilise isiku esindaja nimele ja meiliaadressile samad isikuandmete töötlemise nõuded, nagu kehtivad eraisiku omadele.</p>
<h3>Mida isikuandmetega teha tohib?</h3>
<p>Isikuandmete võlu ja valu seisneb selles, et <b>isikuandmete töötlemiseks (kogumiseks, süstematiseerimiseks, analüüsimiseks, kasutamiseks jne) on alati vaja alust</b>. Euroopa isikuandmete kaitse üldmäärus (GDPR) annab avalikule sektorile nende ülesannete täitmisel andmete töötlemiseks neli peamist alust:
<ol>
<li><b>Seadusest tulenev alus</b>. Üldjuhul tulenebki riigiasutuste õigus kodanike andmeid töödelda konkreetsest seadusest, mis lubab asutusel oma ülesannete täitmiseks isikuandmeid töödelda.</li>
<li><b>Kokkulepe</b>. Tüüpiline näide: kui töötaja on töölepingut sõlmides aktsepteerinud oma tööandjalt mingi eelise, mida tööandja saab osutada ainult töötaja isikuandmeid töödeldes, on töötaja ja tööandja töölepingu sõlmimisega kaudselt teinud kokkuleppe, mis lubab töötaja isikuandmeid töödelda.</li>
<li><b>Seadusest tuleneva kohustuse täitmine</b>. Näiteks raamatupidamise nõuete järgimine.</li>
<li><b>Vabatahtlik informeeritud nõusolek</b>. Isik saab alati anda teisele isikule nõusoleku tema andmete töötlemiseks. Siin on olulised kaks aspekti. <b>Vabatahtlikkus</b> tähendab, et nõusoleku peab saama iga kell tagasi võtta ja mittenõustumisega ei kaasne isikule sanktsioone. <b>Informeeritus</b> tähendab, et andmete töötleja peab andma isikule enne tema nõusoleku võtmist selge ülevaate, kes, kuidas ja mis otstarbel tema andmeid kasutab. Muide, nõusoleku küsimine on lubatud vaid juhul, kui inimesel on ka päriselt võim oma nõusolek tagasi võtta – näiteks ei tohi küsida andmete töötlemiseks nõusolekut, kui andmete töötlemise õigus tuleneb juba seadusest ja isik seda keelata ei saa.</li></ol>
Isikuandmete töötlemise aluseid on muidugi veel (nt õigustatud huvi või erisused andmete kogumiseks riikliku statistika ja teadusuuringute tarbeks), aga sellest ehk pikemalt teinekord.</p>
<p>Nõusolek või kokkulepe ei pea tingimata olema kirjalik, ent andmete töötleja peab olema võimeline tõendama, et nõusolek või kokkulepe on olemas. Seega soovitavad advokaadid siiski fikseerida andmesubjekti nõusolek kirjalikku taasesitamist võimaldavas vormis (nt nõusolekuvorm, e-kiri või süsteemilogi, kui isik on seal tuvastatud). Eriti hea, kui nõusolek on allkirjastatud – siis on raske seda tagantjärele vaidlustada.</p>
<p>Kui isikuandmete töötlemiseks on alus olemas, tuleb andmete töötlemisel silmas pidada kindlaid põhimõtteid (needki on kirjas GDPRis). Kõige olulisemana:
<ol>
<li>Koguda nii vähe isikuandmeid kui võimalik.</li>
<li>Hoida isikuandmeid isikustatud kujul nii lühikest aega kui võimalik – see tähendab võimalikult kiiret pseudonüümimist või kustutamist, kui neid enam vaja ei ole.</li>
<li>Isikuandmete töötlemise eesmärk peab olema läbipaistev.</li>
<li>Töötlemisest peab maha jääma jälg – andmesubjekt peab saama jälgida, kuidas andmeid on töödeldud.</li></ol>
GDPRi juhtmõte on anda võim andmesubjekti kätte. Andmete töötleja seisukohast tähendab see, et  isikuandmete töötleja peab tegema <b>kõik endast oleneva</b>, et töötlemine oleks seaduslik ja läbipaistev.</p>
<h3>Kuidas see avaandmete avaldamist mõjutab?</h3>
<p>Avaliku sektori andmevaldajal oleks justkui dilemma. Ühelt poolt nõuab GDPR isikuandmete kaitsmist, teisalt käsib avaliku teabe seadus (AvTS) avaldada juurdepääsupiiranguteta avalik teave vaikimisi avaandmetena. Kokku saab mitu olulist põhimõtet: ühelt poolt eraelu puutumatus, teisalt riigi läbipaistvus ja avalik aruandekohustus oma kodanike ees, ühelt poolt turvalisus, teiselt poolt võimalus andmete abil uut majanduslikku ja ühiskondlikku väärtust luua. Liisi Jürgen ja Siiri Vello kinnitavad, et andmete avaldamisel tuleb arvestada nii AvTSi kui ka GDPRiga, kuid üks teist ei takista – <b>avaandmeid saab edukalt avaldada nii, et isikute eraelu puutumatuks jääb</b>. Näiteks nii:
<ul>
<li>Kui andmestik sisaldab isikuandmeid, mille avaldamiseks alust ei ole, saab need andmete avaldamisel anonüümida või avaldada suuremateks kogumiteks koondatult, mis üksikute isikute tuvastamist ei võimalda.</li>
<li>Teine võimalus on avaldada andmetest vaid see osa, mis isikuandmeid ei sisalda. Näiteks kui ametiasutuse ametlik vastus kodaniku pöördumisele sisaldab lisaks õiguslikule seisukohale ka isikuandmeid, võib dokumendi avaldada nii, et isikuandmete osa on kustutatud või kinni kaetud. <b>See, et andmestik või dokument sisaldab isikuandmeid, ei anna veel alust piirata juurdepääsu tervele andmestikule</b>.</li></ul></p>  
<h3>Kuidas riske vältida?</h3>
<p>Selleks, et andmete avaldamiseks kõige mõistlikum viis leida, tuleb asutustel läbi viia <b>avaandmete mõjuhinnang</b>. Selle käigus hinnatakse andmete avaldamise kulu ja tulu, võimalikke positiivseid ja negatiivseid mõjusid ning võimalusi tagada teabe avaldamisel eraelu puutumatus, autoriõigused, riiklik julgeolek, ärisaladuse kaitse ja muu juurdepääsupiiranguga teabe kaitse. <b>Alati tuleks küsida, kas isikuandmed saab kuidagi andmete juurest ära võtta, et juurdepääsupiiranguta osa ikkagi avaldada?</b></p>
<p>Hinnata tuleks ka tehnoloogia arenguga kaasnevaid riske: mis on võimalik kahju andmesubjektidele, kui tehnoloogia arenedes on tulevikus võimalik anonüümitud andmetest tagasi jõuda isikuandmeteni? Kui andmete avalikuks tulekuga ei oleks riive isikuandmetele oluline, võib riski võtmine olla õigustatud; kui riive võib olla oluline, tuleks avaldamist põhjalikumalt analüüsida. Kui teabevaldaja on enne andmete avaldamist riske analüüsinud ja suudab seda tõendada, on teda ka raske sanktsioneerida, kui keegi siiski kunagi peaks suutma võetud turvameetmed tagasi pöörata.</p>
<p>See, et andmete avaldamisega kaotab andmevaldaja teatud määral ka kontrolli andmete üle, on paratamatu. Juba avaldatud andmete puhul džinni pudelisse tagasi ei saa, kuid advokaadid rõhutavad, et turvariskid on alati olemas ka siis, kui andmed avaldamata jätta. Just seepärast on oluline asutuse valduses olevaid andmeid terviklikult hallata, tehnoloogia arengul silma peal hoida, avaldada seda, mida saab, ning regulaarselt riskid ja võimalused üle vaadata. Kui mõjuhinnang ütleb, et avatud andmehulgana avaldamine tooks kaasa liigseid riske, ei tähenda see veel, et andmeid üldse avaldada ei tohiks. Näiteks võib olla võimalik osad andmed kättesaadavaks teha süsteemis, mis nõuab kasutaja eelnevat tuvastamist.</p>
<h3>Aga kui piiraks ligipääsu maksumüüriga?</h3>
<p>Töötoas arutati pikalt ka küsimuse üle, kas riigiasutus võib andmetele juurdepääsu piiramiseks kehtestada andmepäringutele tasu. Advokaatide seisukoht oli siin selge: tasu küsimine andmete eest saab olla põhjendatud ainult andmete avaldamise otseste kulude katmiseks, kuid <b>tasu küsimine ei saa olla turvameede</b>. Seevastu võib andmetele maksumüüri seadmine diskrimineerida vähemate ressurssidega ja haavatavaid kasutajarühmi, kes ei saa endale andmete ostmist lubada, kuid võiksid neid vajada. Maksumüür piirab oluliselt võrdset konkurentsi suurkorporatsioonide ja väikeettevõtete vahel ning piirab huvikaitseühenduste ligipääsu neile olulistele andmetele, kuid ilmselt ei hoia eemal hästi rahastatud pahatahtlikke kasutajaid. Advokaadid leidsid, et väärkasutuse riskide maandamiseks on hoopis kohasem meede näiteks päringute arvu piiramine, mitte aga tasu küsimine.</p>
<h3>Neli juhtmõtet</h3>
<p>Kokkuvõttes jäi töötoast kõlama neli olulist mõtet:
<ol>
<li>Isikuandmete kaitse ei takista avaandmete avaldamist. Alati tuleks analüüsida, kas isikuandmed saab kuidagi andmete juurest ära võtta, et juurdepääsupiiranguta osa siiski avatuks teha.</li>
<li>Andmekaitse on ainult üks komponent kaalukausil – samavõrra oluline on kaaluda andmete avamise majanduslikku ja ühiskondlikku väärtust.</li>
<li>Tark ei torma, aga otsustamatusse ei tohi kinni jääda. Kui andmete avaldamisega võib kaasneda riske, tuleb riske põhjalikumalt kaaluda või avaldada andmetest vaid teatud osa, mitte aga riskide kartuses avaldamisest sootuks loobuda.</li>
<li>Maksumüür ei ole turvameede! Avaliku teabe eest võib tasu küsida üksnes andmete avaldamise kulu korvamiseks (ja ainult selles ulatuses).</li></p>
______
<p><em>Avaandmete portaali sisustatakse Euroopa Liidu struktuuritoetuse toetusskeemist „Infoühiskonna teadlikkuse tõstmine“, mida rahastab Euroopa Regionaalarengu Fond. Projekti tegevused viib läbi MTÜ Open Knowledge Estonia.</em></p>'
---
